executable            = /afs/cern.ch/user/d/driosper/bsm3g_coffea/condor/submit.sh
arguments             = $(JOBNUM) /afs/cern.ch/user/d/driosper/bsm3g_coffea /afs/cern.ch/user/d/driosper/private/x509up_u182284
output                = /afs/cern.ch/user/d/driosper/bsm3g_coffea/condor/logs/qcd_tf_mu/2022preEE/DYJetsToLL_inclusive_10to50/qcd_tf_mu_DYJetsToLL_inclusive_10to50.$(ClusterId).$(ProcId).out
error                 = /afs/cern.ch/user/d/driosper/bsm3g_coffea/condor/logs/qcd_tf_mu/2022preEE/DYJetsToLL_inclusive_10to50/qcd_tf_mu_DYJetsToLL_inclusive_10to50.$(ClusterId).$(ProcId).err
log                   = /afs/cern.ch/user/d/driosper/bsm3g_coffea/condor/logs/qcd_tf_mu/2022preEE/DYJetsToLL_inclusive_10to50/qcd_tf_mu_DYJetsToLL_inclusive_10to50.$(ClusterId).$(ProcId).log

should_transfer_files = YES
transfer_input_files  = /afs/cern.ch/user/d/driosper/bsm3g_coffea/condor/qcd_tf_mu/2022preEE/DYJetsToLL_inclusive_10to50/partitions.json,/afs/cern.ch/user/d/driosper/bsm3g_coffea/condor/qcd_tf_mu/2022preEE/DYJetsToLL_inclusive_10to50/missing.txt,/afs/cern.ch/user/d/driosper/bsm3g_coffea/condor/qcd_tf_mu/2022preEE/DYJetsToLL_inclusive_10to50/arguments.json

request_memory        = 2000M

+JobFlavour           = "longlunch"
+SingularityImage     = "/cvmfs/unpacked.cern.ch/registry.hub.docker.com/coffeateam/coffea-dask:latest-py3.9"

Queue JOBNUM from /afs/cern.ch/user/d/driosper/bsm3g_coffea/condor/qcd_tf_mu/2022preEE/DYJetsToLL_inclusive_10to50/missing.txt