executable            = /afs/cern.ch/user/d/driosper/bsm3g_coffea/condor/submit.sh
arguments             = $(JOBNUM) /afs/cern.ch/user/d/driosper/bsm3g_coffea /afs/cern.ch/user/d/driosper/private/x509up_u182284
output                = /afs/cern.ch/user/d/driosper/bsm3g_coffea/condor/logs/ztomumu/2023postBPix/WZ/ztomumu_WZ.$(ClusterId).$(ProcId).out
error                 = /afs/cern.ch/user/d/driosper/bsm3g_coffea/condor/logs/ztomumu/2023postBPix/WZ/ztomumu_WZ.$(ClusterId).$(ProcId).err
log                   = /afs/cern.ch/user/d/driosper/bsm3g_coffea/condor/logs/ztomumu/2023postBPix/WZ/ztomumu_WZ.$(ClusterId).$(ProcId).log

should_transfer_files = YES
transfer_input_files  = /afs/cern.ch/user/d/driosper/bsm3g_coffea/condor/ztomumu/2023postBPix/WZ/partitions.json,/afs/cern.ch/user/d/driosper/bsm3g_coffea/condor/ztomumu/2023postBPix/WZ/jobnum.txt,/afs/cern.ch/user/d/driosper/bsm3g_coffea/condor/ztomumu/2023postBPix/WZ/arguments.json

+JobFlavour           = "longlunch"
+SingularityImage     = "/cvmfs/unpacked.cern.ch/registry.hub.docker.com/coffeateam/coffea-dask:latest-py3.9"

Queue JOBNUM from /afs/cern.ch/user/d/driosper/bsm3g_coffea/condor/ztomumu/2023postBPix/WZ/jobnum.txt