executable            = CONDORDIR/submit.sh
arguments             = $(JOBNUM) BASEDIR X509PATH
output                = LOGDIR/JOBNAME.$(ClusterId).$(ProcId).out
error                 = LOGDIR/JOBNAME.$(ClusterId).$(ProcId).err
log                   = LOGDIR/JOBNAME.$(ClusterId).log

should_transfer_files = YES
transfer_input_files  = INPUTFILES

request_memory        = MEMORYM

+JobFlavour           = "longlunch"
+SingularityImage     = "/cvmfs/unpacked.cern.ch/registry.hub.docker.com/coffeateam/coffea-dask-almalinux9:2026.5.0-py3.13"

on_exit_remove        = (ExitBySignal == False) && (ExitCode == 0)
max_retries           = 3
periodic_release      = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 300) && (NumJobStarts < 3)

Queue JOBNUM from JOBNUM_FILE